apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - postgresql-cluster.yaml
  - m3u-editor-pvc.yaml
  - jellyfin-pvc.yaml
  - jellyfin-http-route.yaml
  - m3u-editor-deployment.yaml
  - m3u-editor-service.yaml
  - m3u-editor-http-route.yaml
helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    releaseName: jellyfin
    namespace: media
    valuesFile: jellyfin-values.yaml
