apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Gateway resources
  - gateway-class.yaml
  - namespace.yaml
  - gateway-external.yaml
  - gateway-internal.yaml
  - cert-coruscant.yaml


generatorOptions:
  disableNameSuffixHash: true
