apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: postgres-operator
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    version: v1.14.0 # renovate: github-releases=zalando/postgres-operator
    releaseName: postgres-operator
    namespace: postgres-operator
    valuesFile: values.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
